version: '3'

services: 
  gerrit:
    image: openfrontier/gerrit:2.14.3
    container_name: gerrit
    environment:
      AUTH_TYPE: DEVELOPMENT_BECOME_ANY_ACCOUNT
      DATABASE_TYPE: mysql
      DB_PORT_3306_TCP_ADDR: mysql
      DB_PORT_3306_TCP_PORT: 3306
      DB_ENV_MYSQL_DB: 'gerrit?useUnicode=true&characterEncoding=utf8&useSSL=false'
      DB_ENV_MYSQL_USER: root
      DB_ENV_MYSQL_PASSWORD: 123456
    volumes:
      - ../common/conf/localtime:/etc/localtime:ro
      - ../common/conf/timezone:/etc/timezone:ro
      - ./volume-gerrit/:/var/gerrit/review_site/
    networks:
      - xbug-network
    domainname: xbug-network
    hostname: gerrit
    external_links:
      - mysql
    ports:
      - 29411:29418
      - 8080:8080

networks:
  xbug-network:
    external: true  