version: '3'

services: 
  jenkins:
    image: jenkins:2.60.3
    container_name: jenkins
    ports:
      - 18080:8080
      - 50000:50000
    volumes:
      - ../common/conf/localtime:/etc/localtime:ro
      - ../common/conf/timezone:/etc/timezone:ro
      - ./volume-jenkins/jenkins_home:/var/jenkins_home
    networks:
      - xbug-network

networks:
  xbug-network:
    external: true  