version: '3'

services: 
  hive-base:
    image: lsw1991abc/hive-base:2.3.0
    container_name: hive-base
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./hadoop-single/:/opt/data/
      - ./hive-base/:/opt/hive-data/
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
      - ./apache-hive-2.3.0-bin/conf/:/opt/apache-hive-2.3.0-bin/conf/
      - ./apache-hive-2.3.0-bin/lib/mysql-connector-java-5.1.44-bin.jar:/opt/apache-hive-2.3.0-bin/lib/mysql-connector-java-5.1.44-bin.jar
    networks:
      - xbug-network
    domainname: xbug-network
    hostname: hive-base
    ports:
      - 50070:50070
      - 8020:8020
      - 8088:8088
      - 9000:9000
      - 9083:9083
      - 10000:10000

networks:
  xbug-network:
    external: true  