version: '3'

services: 

  namenode01:
    image: lsw1991abc/hadoop-base:2.7.4
    container_name: namenode01
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./namenode01:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    external_links:
      - zookeeper01
      - zookeeper02
      - zookeeper03
    networks:
      - xbug-network
    ports:
      - 50071:50070
      - 8021:8020
      - 8081:8088
      - 9001:9000

  namenode02:
    image: lsw1991abc/hadoop-base:2.7.4
    container_name: namenode02
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./namenode02:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    external_links:
      - zookeeper01
      - zookeeper02
      - zookeeper03
    networks:
      - xbug-network
    ports:
      - 50072:50070
      - 8022:8020
      - 8082:8088
      - 9002:9000

  journalnode01:
    image: lsw1991abc/hadoop-base:2.7.4
    container_name: journalnode01
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./journalnode01:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network

  journalnode02:
    image: lsw1991abc/hadoop-base:2.7.4
    container_name: journalnode02
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./journalnode02:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network

  journalnode03:
    image: lsw1991abc/hadoop-base:2.7.4
    container_name: journalnode03
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./journalnode03:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network

  datanode01:
    image: lsw1991abc/hadoop-base:2.7.4
    container_name: datanode01
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./datanode01:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network

  datanode02:
    image: lsw1991abc/hadoop-base:2.7.4
    container_name: datanode02
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./datanode02:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network

  datanode03:
    image: lsw1991abc/hadoop-base:2.7.4
    container_name: datanode03
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./datanode03:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network

networks:
  xbug-network:
    external: true  