version: '3'

services: 

  zookeeper01:
    image: zookeeper:3.4
    container_name: zookeeper01
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper01:2888:3888 server.2=zookeeper02:2888:3888 server.3=zookeeper03:2888:3888
    volumes:
      - ./zookeeper01:/data
    networks:
      - xbug-network

  zookeeper02:
    image: zookeeper:3.4
    container_name: zookeeper02
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper01:2888:3888 server.2=zookeeper02:2888:3888 server.3=zookeeper03:2888:3888
    volumes:
      - ./zookeeper02:/data
    networks:
      - xbug-network

  zookeeper03:
    image: zookeeper:3.4
    container_name: zookeeper03
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper01:2888:3888 server.2=zookeeper02:2888:3888 server.3=zookeeper03:2888:3888
    volumes:
      - ./zookeeper03:/data
    networks:
      - xbug-network



  namenode01:
    image: lsw1991abc/hadoop-base:0.1
    container_name: namenode01
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./namenode01:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network
    ports:
      - 50071:50070
      - 8021:8020
      - 8081:8088
      - 9001:9000

  namenode02:
    image: lsw1991abc/hadoop-base:0.1
    container_name: namenode02
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./namenode02:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network
    ports:
      - 50072:50070
      - 8022:8020
      - 8082:8088
      - 9002:9000



  journalnode01:
    image: lsw1991abc/hadoop-base:0.1
    container_name: journalnode01
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./journalnode01:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network

  journalnode02:
    image: lsw1991abc/hadoop-base:0.1
    container_name: journalnode02
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./journalnode02:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network

  journalnode03:
    image: lsw1991abc/hadoop-base:0.1
    container_name: journalnode03
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./journalnode03:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network



  datanode01:
    image: lsw1991abc/hadoop-base:0.1
    container_name: datanode01
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./datanode01:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network

  datanode02:
    image: lsw1991abc/hadoop-base:0.1
    container_name: datanode02
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./datanode02:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network

  datanode03:
    image: lsw1991abc/hadoop-base:0.1
    container_name: datanode03
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./datanode03:/opt/data
      - ./hadoop-2.7.4/etc/hadoop/:/opt/hadoop-2.7.4/etc/hadoop/
    networks:
      - xbug-network


networks:
  xbug-network:
    external: true  