version: '3'

services: 
  hbase-master01:
    image: lsw1991abc/hbase-base:1.3.1
    container_name: hbase-master01
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./hbase-master01/:/opt/data/
      - ./hbase-1.3.1/conf/:/opt/hbase-1.3.1/conf/
      - ./hadoop-2.7.4/:/opt/hadoop-2.7.4/
    external_links:
      - zookeeper01
      - zookeeper02
      - zookeeper03
    networks:
      - xbug-network
    domainname: xbug-network
    hostname: hbase-master01
    ports:
      - 16011:16010

  hbase-master02:
    image: lsw1991abc/hbase-base:1.3.1
    container_name: hbase-master02
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./hbase-master02/:/opt/data/
      - ./hbase-1.3.1/conf/:/opt/hbase-1.3.1/conf/
      - ./hadoop-2.7.4/:/opt/hadoop-2.7.4/
    external_links:
      - zookeeper01
      - zookeeper02
      - zookeeper03
    networks:
      - xbug-network
    domainname: xbug-network
    hostname: hbase-master02
    ports:
      - 16012:16010

  hbase-regionserver01:
    image: lsw1991abc/hbase-base:1.3.1
    container_name: hbase-regionserver01
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./hbase-regionserver01/:/opt/data/
      - ./hbase-1.3.1/conf/:/opt/hbase-1.3.1/conf/
      - ./hadoop-2.7.4/:/opt/hadoop-2.7.4/
    external_links:
      - zookeeper01
      - zookeeper02
      - zookeeper03
    networks:
      - xbug-network
    domainname: xbug-network
    hostname: hbase-regionserver01
    ports:
      - 16031:16030

  hbase-regionserver02:
    image: lsw1991abc/hbase-base:1.3.1
    container_name: hbase-regionserver02
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./hbase-regionserver02/:/opt/data/
      - ./hbase-1.3.1/conf/:/opt/hbase-1.3.1/conf/
      - ./hadoop-2.7.4/:/opt/hadoop-2.7.4/
    external_links:
      - zookeeper01
      - zookeeper02
      - zookeeper03
    networks:
      - xbug-network
    domainname: xbug-network
    hostname: hbase-regionserver02
    ports:
      - 16032:16030

  hbase-regionserver03:
    image: lsw1991abc/hbase-base:1.3.1
    container_name: hbase-regionserver03
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./hbase-regionserver03/:/opt/data/
      - ./hbase-1.3.1/conf/:/opt/hbase-1.3.1/conf/
      - ./hadoop-2.7.4/:/opt/hadoop-2.7.4/
    external_links:
      - zookeeper01
      - zookeeper02
      - zookeeper03
    networks:
      - xbug-network
    domainname: xbug-network
    hostname: hbase-regionserver03
    ports:
      - 16033:16030

networks:
  xbug-network:
    external: true  